Hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls", namespace="pages")),  # Main page URL
    path("accounts/", include("accounts.urls")),
    path("chat/", include("chat.urls")),
    path("patients/", include("patients.urls")),
    path("doctor/", include("doctor.urls")),
    path('api1/', include("api1.urls")),
    path('api2/', include('api2.urls')),
    path('api3/', include('api3.urls')),
    path('api4/', include("api4.urls")),
    path('api5/', include("api5.urls")),
    path('api6/', include("api6.urls")),
]

# Serving media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT[0])

accounts/urls.py
from django.urls import path
from accounts import views
from .forms import CustomPasswordResetForm, CustomSetPasswordForm

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.loginUser, name="loginAccount"),
    path("logout/", views.logoutUser, name="logoutAccount"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    # Password Reset URLs
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path("password_reset_done/", views.password_reset_done, name="password_reset_done"),
    path(
        "reset/<uidb64>/<token>/",
        views.password_reset_confirm,
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        views.password_reset_complete,
        name="password_reset_complete",
    ),
]

api/urls.py
from django.urls import path
from .views import FoodItemListCreate, OrderListCreate, FoodItemDetail

urlpatterns = [
    path('fooditems/', FoodItemListCreate.as_view(), name='fooditem-list-create'),
    path('fooditems/<int:pk>/', FoodItemDetail.as_view(), name='fooditem-detail'),
    path('orders/', OrderListCreate.as_view(), name='order-list-create'),
    path('fooditems/<int:pk>/', FoodItemDetail.as_view(), name='fooditem-detail'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chat_room_list, name="chat_room_list"),
    path("<int:pk>/", views.chat_room_detail, name="chat_room_detail"),
    path("private/", views.private_message_list, name="private_message_list"),
    path(
        "private/<str:username>/",
        views.private_message_detail,
        name="private_message_detail",
    ),
    path("logoutChat/", views.logoutChat, name="logoutChat"),
]

doctor/urls.py
from django.urls import path
from . import views

app_name = "doctor"

urlpatterns = [
    path("doctor_appointments/", views.doctor_appointments, name="doctor_appointments"),
    path(
        "doctor_appointments/<int:pk>/status/",
        views.update_appointment_status,
        name="update_appointment_status",
    ),
    path("static-file-debug/", views.static_file_debug, name="static_file_debug"),
    path("contact/patient/", views.doctor_contact, name="doctor_contact"),
    path("messages/", views.doctor_messages, name="doctor_messages"),
]

pages/urls.py
from django.urls import path
from pages import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),  # This should be publicly accessible
    path("about", views.about, name="about"),
    path("services", views.services, name="services"),
    path("contact", views.contact, name="contact"),
    path("authenticated_home/", views.authenticated_home, name="authenticated_home"),
]


handler404 = "pages.views.custom_404"

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('profile/', include('profiles.urls')),
    path('shop/', include('shop.urls')),
    path('api/', include('api.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/templates/base.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ page_title }}{% endblock %}</title>
    <!-- Bootstrap CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
{% if request.user.is_authenticated %}
<header>
    <div class="container-fluid">
        <div class="row">
            <!-- Welcome Message -->
            <div class="col-md-4 col-sm-12 text-left d-flex align-items-center">
                <span>Welcome to a Professional Health Care</span>
            </div>

            <!-- Contact Info -->
            <div class="col-md-4 col-sm-12 text-center bg-primary text-white py-2 d-flex align-items-center justify-content-center">
                <span class="phone-icon mr-3"><i class="fa fa-phone"></i>Call Us: 010-060-0160</span>
                <span class="date-icon"><i class="fa fa-calendar-plus-o"></i>Duration: 6:00 AM - 10:00 PM (Mon-Fri)</span>
            </div>

            <!-- Email -->
            <div class="col-md-4 col-sm-12 text-right bg-dark text-white py-2 d-flex align-items-center justify-content-end">
                <span class="email-icon"><i class="fas fa-envelope ml-1"></i> <a href="mailto:ivoryhospital12@company.com" class="text-white">Email: ivoryhospital12@company.com</a></span>
            </div>
        </div>
    </div>
</header>
{% endif %}
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary no-space" style="margin: 0; padding: 0;">
        <a class="navbar-brand" href="{% url 'pages:home' %}">Ivory Specialist Hospital</a>
        
        {% if request.user.is_authenticated %}
            {% if request.user.role == "doctor" %}
                <a href="{% url 'doctor:doctor_appointments' %}" class="btn btn-primary">See Appointments</a>
            {% elif request.user.role == "patient" %}
                <a href="{% url 'patients:patient_appointments' %}" class="btn btn-primary">Book Appointments</a>             
            {% endif %}
        {% endif %}
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'pages:authenticated_home' %}">Home</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'about' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'pages:about' %}">About Us</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'services' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'pages:services' %}">Services</a>
                    </li>
                    
                    {% if request.user.role|lower == "doctor" %}
                    <li class="nav-item {% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'doctor:doctor_contact' %}">
                        Contact
                        </a>
                    </li>
                    {% elif request.user.role|lower == "patient" %}
                    <li class="nav-item {% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'patients:patient_contact' %}">
                        Contact
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url 'chat:chat_room_list' %}">
                            Chat <i class="fas fa-comments"></i>
                        </a>
                    </li>

                    {% if request.user.role == "doctor" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'doctor:doctor_messages' %}">
                            <i class="fas fa-envelope ml-1"></i>
                        </a>
                    </li>
                {% elif request.user.role == "patient" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'patients:patient_messages' %}">
                            <i class="fas fa-envelope ml-1"></i>
                        </a>
                    </li>
                {% endif %}
                    
                    <li class="nav-item">
                        <a class="nav-link nav-link-icon" href="{% url 'accounts:profile' %}">
                            <i class="fas fa-user-circle fa-2x"></i>
                            Profile
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="btn-btn solid-border btn-round-full" href="{% url 'accounts:logoutAccount' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn-btn solid-border btn-round-full" href="{% url 'accounts:loginAccount' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn-btn solid-border btn-round-full" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    {% if request.user.is_authenticated %}
    <!-- Optional Footer -->
    <footer class="bg-dark text-white text-center py-4">
        <p>&copy; 2024 Ivory Hospital. All Rights Reserved.</p>
        <ul class="list-unstyled">
            <li><a href="#" class="text-white">Privacy Policy</a></li>
            <li><a href="#" class="text-white">Terms of Service</a></li>
        </ul>
    </footer>
    {% endif %}

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>